### PR TITLE
Config select

### PR DESCRIPTION
**Pull request by ilijamt**
This will allow you to create different configurations for a game instead of just copying the file to a different name like it's explained in http://danielgibbs.co.uk/lgsm/csgoserver/#Multiple_Servers.

The way it works is it looks for any files that have extension **appid** which is the app id for the game on steam.

If there are no files like that or if there is only one file, then the script behaves the same as before this modification.

If there is more than one available config then you will have to select which one you want to use.

Example:

##### csgo_tick64.740
```
#!/bin/bash
tickrate="64"
port="27015"
sourcetvport="27020"
clientport="27005"
```

##### csgo_tick128.740
```
#!/bin/bash
tickrate="128"
port="27016"
sourcetvport="27021"
clientport="27006"
servicename="csgo-server128"
```

````bash
$ ./csgoserver
[ WARN ] configuration file not specified, use one of the available ones (csgo_tick64|csgo_tick128)
Usage: ./csgoserver {start|stop|restart|update|update-restart|validate|validate-restart|monitor|email-test|details|backup|console|debug|install|auto-install} csgo_tick64|csgo_tick128
```

So when you have multiple configuration the only thing that changes is that you add the configuration to the end of the command 

```bash
$ ./csgoserver start csgo_tick64
```

You can use the configs to override any configuration necessary in the file.

The new file *fn_select*, I didn't go over all the games to see which variables need to be reinitialized so if there are different variables for different games, they will have to be added at the end of the script in the case.

This should work on all games that are available that use steam

The snippet bellow will need to be added to the file https://github.com/dgibbs64/linuxgameservers/blob/master/CounterStrikeGlobalOffensive/csgoserver#L114

```bash
# init the getopt function variables
getopt=$1

# init the select function variables
usesrvcfg=1
getsrvcfg=$2

fn_select
fn_getopt
```

**usesrvcfg** is a safeguard that tells us if this option is enabled or not for the game

### CODE REVIEW

**Comment by ilijamt** [comment]
Only the CounterStrikeGlobalOffensive script has been modified as that is the only game server that I'm hosting, so I could only test on that one.

**Comment by dgibbs64** [comment]
Thanks for this I will look at this feature fully when I have some time :-)

**Comment by Scarsz** [comment]
I'm not sure which command would process it but adding in a command like `./csgoserver cfgdiff csgo_tick64 csgo_tick128` to compare the differences of two config files would be helpful

**Comment by ilijamt** [comment]
You can check with the details function of the command to see the differences.

As for adding a **cfgdiff** command in bash it would be tricky, as to actually compare them you will have to load them and then compare them.

I will see what I can do about adding a cfgdiff command.

Here is what says on my server.

```bash
$ ./csgoserver details csgo_tick64
Distro Details
=============================================================================================================================================================================================================================================
Distro:    Debian GNU/Linux 8.0 (jessie)
Arch:      x86_64
Kernel:    3.2.0-4-amd64
Hostname:  vm
tmux:      tmux 1.9
GLIBC:     2.19

Performance
=============================================================================================================================================================================================================================================
Uptime:    16d, 9h, 11m
Avg Load:  0.07, 0.07, 0.05

Mem:       total   used   free
Physical:  5.8G    5.1G   789M
Swap:      1.3G    33M    1.2G

Disk Usage
=============================================================================================================================================================================================================================================
Disk available:  3.7G
Serverfiles:     9.6G

Counter Strike: Global Offensive Server Details
=============================================================================================================================================================================================================================================
Server name:    ilijamt CSGO Server (64 tick)
Server IP:      <IP>:27015
RCON password:  <RCON_PASSWORD>
Status:         ONLINE

Service name:  csgo-server64
User:          csgoserver
Location:      /home/csgoserver
Config file:   /home/csgoserver/serverfiles/csgo/cfg/csgo-server64.cfg

Backups
=============================================================================================================================================================================================================================================
No Backups created

Command-line Parameters
=============================================================================================================================================================================================================================================
./srcds_run -game csgo -usercon -strictportbind -ip <IP> -port 27015 +clientport 27005 +tv_port 27020 -tickrate 64 +map de_dust2 +servercfgfile csgo-server64.cfg -maxplayers_override 10 +mapgroup random_classic +game_mode 1 +game_type 0 +host_workshop_collection  +workshop_start_map  -authkey

Ports
=============================================================================================================================================================================================================================================
Change ports by editing the command-line
parameters in csgoserver.

Useful port diagnostic command:
netstat -atunp | grep srcds_linux

DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game/RCON  INBOUND    27015  tcp/udp
> SourceTV   INBOUND    27020  udp
< Client     OUTBOUND   27005  udp

Status: ONLINE
```

```
$ ./csgoserver details csgo_tick64
Distro Details
=============================================================================================================================================================================================================================================
Distro:    Debian GNU/Linux 8.0 (jessie)
Arch:      x86_64
Kernel:    3.2.0-4-amd64
Hostname:  vm
tmux:      tmux 1.9
GLIBC:     2.19

Performance
=============================================================================================================================================================================================================================================
Uptime:    16d, 9h, 12m
Avg Load:  0.12, 0.08, 0.05

Mem:       total   used   free
Physical:  5.8G    5.1G   786M
Swap:      1.3G    33M    1.2G

Disk Usage
=============================================================================================================================================================================================================================================
Disk available:  3.7G
Serverfiles:     9.6G

Counter Strike: Global Offensive Server Details
=============================================================================================================================================================================================================================================
Server name:    ilijamt CSGO Server (128 tick)
Server IP:      <IP>:27016
RCON password:  <RCON>
Status:         ONLINE

Service name:  csgo-server128
User:          csgoserver
Location:      /home/csgoserver
Config file:   /home/csgoserver/serverfiles/csgo/cfg/csgo-server128.cfg

Backups
=============================================================================================================================================================================================================================================
No Backups created

Command-line Parameters
=============================================================================================================================================================================================================================================
./srcds_run -game csgo -usercon -strictportbind -ip <IP> -port 27016 +clientport 27006 +tv_port 27021 -tickrate 128 +map de_dust2 +servercfgfile csgo-server128.cfg -maxplayers_override 10 +mapgroup random_classic +game_mode 1 +game_type 0 +host_workshop_collection  +workshop_start_map  -authkey

Ports
=============================================================================================================================================================================================================================================
Change ports by editing the command-line
parameters in csgoserver.

Useful port diagnostic command:
netstat -atunp | grep srcds_linux

DESCRIPTION  DIRECTION  PORT   PROTOCOL
> Game/RCON  INBOUND    27016  tcp/udp
> SourceTV   INBOUND    27021  udp
< Client     OUTBOUND   27006  udp

Status: ONLINE
```

**Comment by ilijamt** [comment]
Is this gonna be merged ?

**Comment by dgibbs64** [comment]
There is a server I am currently working (Running with Rifles) that have multiple configuration files available. I believe this setup may be useful for this requirement.

**Comment by dgibbs64** [comment]
Finally got my head around this haha. I will get this working with Running with Rifles First then I will start adding to other servers as required. I will be thinking of a way to display to the end user where the settings are coming from so it is clear how they are being gathered.

e.g 

    port="27015" > csgoserver
    gamemode="0" > csgoserver128.740
    gametype="0" > csgoserver128.740
    defaultmap="de_dust2" > csgoserver
    mapgroup="random_classic" > csgoserver128.740
    maxplayers="16" > csgoserver
    tickrate="128" > csgoserver128.740
    ip="0.0.0.0"  > csgoserver

**Comment by ilijamt** [comment]
The best way to do what you want is to hold all the settings in an array, or use a function to set them that way you can just iterate over the array to show which settings came from where.

Though it will complicate things a little, but here you go a working example that will work

**csgoserver**
```
#!/bin/bash
declare -A opts

setparam() {
  fl="$3"
  if [ -z "$3" ]; then
    fl=$(basename $0)
  fi
  export $1="$2"
  opts[$1]="$1=$2 > $fl"
}

setparam port "27015"
setparam gametype "0"
setparam defaultmap "de_dust2"
setparam mapgroup "random_classic"
setparam maxplayers "16"
setparam tickrate "128"
setparam ip "0.0.0.0"

. csgoserver128.740
echo "Loop over opts array"
for i in "${!opts[@]}"
do
  echo "${opts[$i]}"
done

echo
echo "Line by line echo"
echo "port=$port"
echo "gamemode=$gamemode"
echo "defaultmap=$defaultmap"
echo "mapgroup=$mapgroup"
echo "maxplayers=$maxplayers"
echo "tickrate=$tickrate"
echo "ip=$ip"
echo "test=$test"
```

**csgoserver128.740** 
```
#!/bin/bash

_setparam() {
  setparam "$1" "$2" "$BASH_ARGV"
}

_setparam port 27018
_setparam test 2704
```

And the output
```
Loop over opts array
tickrate=128 > csgoserver
gametype=0 > csgoserver
maxplayers=16 > csgoserver
test=2704 > csgoserver128.740
mapgroup=random_classic > csgoserver
defaultmap=de_dust2 > csgoserver
port=27018 > csgoserver128.740
ip=0.0.0.0 > csgoserver

Line by line echo
port=27018
gamemode=
defaultmap=de_dust2
mapgroup=random_classic
maxplayers=16
tickrate=128
ip=0.0.0.0
test=2704
```

Here you go, this will also work with included files, you can try the two scripts and you should get the feel of how it works.

**Comment by ilijamt** [comment]
So you need to just replace where you set the variables with a function to set them and that should be it, shouldn't be too difficult of a change

**Comment by dgibbs64** [comment]
Thanks for this. Just found out Running With Rifles requires two files to run at once :-/ What a pain. I can see this server will take a while

**Pull request merged**
