### PR TITLE
Hurt world

### PR DESCRIPTION
**Pull request by Dids91**
;-)

### CODE REVIEW

**Comment by dgibbs64** [comment]
I will merge when its ready.

**Comment by UltimateByte** [comment]
Can you test it and tell me if anything is wrong ?
It would be relevant to test 7dtd too, as some functions were a bit changed to work as gamename instead of engine, but i don't own the game so i can't check that myself.

**Comment by dgibbs64** [comment]
Its the next thing for me to check :). Im out tonight but I will look as soon as I can.

**Comment by UltimateByte** [comment]
Nice, now it only misses http://gameservermanagers.com/lgsm/hwserver ! :p

**Pull request merged**
