### PR TITLE
adding Quake Live

### PR DESCRIPTION
**Pull request by hurdad**
Ubuntu 14.04 x64

### CODE REVIEW

**Comment by UltimateByte** [comment]
Isn't there an installer or monitor function ?
Pretty cool already btw.

**Comment by dgibbs64** [comment]
Good stuff as always :-). I will take a look later on.

**Comment by hurdad** [comment]
Quake Live has moved to steam as of Oct 2015 http://store.steampowered.com/app/282440/

**Comment by hurdad** [comment]
check updates.
Note: some variables have to be set in commandline, they do not work in server.cfg

**Comment by UltimateByte** [comment]
Wonderful ! I'm glad i bought the Quake pack years ago, and got this for free :D 
I can't wait to make a Quake server !

**Pull request merged**
