### PR TITLE
adding Sven Coop 5.0

### PR DESCRIPTION
**Pull request by hurdad**
Ubuntu 14.04 LTS 32-bit

### CODE REVIEW

**Comment by dgibbs64** [comment]
I love this type of pull request :-). I'm going to need to implement a better file download function to handle non steam files. I will look at this later

**Comment by hurdad** [comment]
they just added sven cop to steam [http://store.steampowered.com/app/225840/]

**Comment by dgibbs64** [comment]
O well thats OK then ;-P

**Comment by olliee** [comment]
I see the SvenCoop folder, but not documentation and I tried running myself however it is having an error with permissions check. Has this been implemented or is it still in progress?

**Comment by hurdad** [comment]
what error are you getting? Should be working. I think there is an additional dependency for sven coop : libssl1.0.0:i386

**Comment by olliee** [comment]
@hurdad http://prntscr.com/blfwx0

**Comment by hurdad** [comment]
looks like you have an OS with an older version of GLIBC. What OS are you running? Sven Coop requires 2.18+

https://github.com/dgibbs64/linuxgsm/wiki/Glibc#server-requirements

Your going to need to use Ubuntu 14.04+, which has GLIBC (2.19)

**Pull request merged**
