### PR TITLE
monitor start

### PR DESCRIPTION
**Pull request by PhilPhonic**
ability to start a server if there is no lockfile

### CODE REVIEW

**Comment by PhilPhonic** [comment]
Couldn't test all servers, because I don't own all the games.
I think this should work for every game..

**Comment by dgibbs64** [comment]
Looks like this is a lockfiles bypass. What is your main reason for wanting this? The lockfile prevents monitor from starting back up if the user specifically stopped the server.

**Comment by PhilPhonic** [comment]
The lockfile still can prevent monitor from starting the server when setting startonmonitor="off" (default).
There is no "reason" why I'm wanting this feature, I just thought it would be helpful. Perhaps there is a constellation of thingst that can happen, where the server crashes and the lockfile is removed? In this case monitor would restart the server.
If there is no way this could happen, just deny my pull request ;)

**Comment by dgibbs64** [comment]
the lock file is only removed on stop and created with start. The only way there could be an issue is if the user deleted the lock file and the monitor would stop working.

If the server crashes and reboots the lockfile still exists so monitor will then start the server again.

I will deny this pull request on this occasion :)

**Pull request closed without merging**
