### PR TITLE
ts3 filename fix

### PR DESCRIPTION
**Pull request by hurdad**

### CODE REVIEW

**Comment by hurdad** [comment]
not sure if need that merge remote..

**Comment by UltimateByte** [comment]
Dude, i already pulled that https://github.com/dgibbs64/linuxgsm/commit/d59bd57d44e820b355b4280756213b2a3962ba01
+ you forgot to change the rm filename with it

I still have issues updating a freshly updated server. There will be something more to check, watch this out : 
https://github.com/dgibbs64/linuxgsm/issues/672

**Comment by hurdad** [comment]
yes ignore this then. also, on 32-bit OS the script keeps trying to install lib32gcc1... which doesn't exist in 32bit OS. fyi

```

/ts3server start
[ WARN ] Starting ts3-server: Checking dependencies: Dependency missing: lib32gcc1
[ INFO ] Starting ts3-server: Attempting to install missing dependencies automatically
sudo dpkg --add-architecture i386; sudo apt-get install lib32gcc1
```

**Comment by UltimateByte** [comment]
No problem mate, you tried ! Maybe update your repo before next time :p 
I'm not done yet either btw !

**Comment by dgibbs64** [comment]
Please add a bug issue for.

> yes ignore this then. also, on 32-bit OS the script keeps trying to install lib32gcc1... which doesn't exist in 32bit OS. fyi
> 
> 
> /ts3server start
> [ WARN ] Starting ts3-server: Checking dependencies: Dependency missing: lib32gcc1
> [ INFO ] Starting ts3-server: Attempting to install missing dependencies automatically
> sudo dpkg --add-architecture i386; sudo apt-get install lib32gcc1

**Comment by UltimateByte** [comment]
Done :)

**Pull request closed without merging**
