### PR TITLE
adding Unreal Tournament (Alpha)

### PR DESCRIPTION
**Pull request by hurdad**
Docs : 

- https://wiki.unrealengine.com/Servers_(Unreal_Tournament)#Initial_Linux_Server_Setup

Server Files URL Published Here : 

- https://www.epicgames.com/unrealtournament/forums/showthread.php?12011-Unreal-Tournament-Pre-Alpha-Playable-Build

### CODE REVIEW

**Comment by UltimateByte** [comment]
Wow, nice.

**Comment by dgibbs64** [comment]
If I was on Tinder I would super like you!

**Comment by UltimateByte** [comment]
Hahaha, LMAO

**Comment by dgibbs64** [comment]
Do you know how the servers are updated?

**Comment by dgibbs64** [comment]
I am merging. There are a few features I will ad myself. I also need to look in to these hubs and make sure that a hub can be setup out of the box. Will need to make sure there is enough documentation on the Wiki to allow users to easily switch between hubs and old school servers

**Comment by dgibbs64** [comment]
@hurdad if you want I am happy to add you as a collaborator on the project. So you can create your own branches and no more pull requests

**Pull request merged**
