### PR TITLE
Update monitor_gsquery.sh

### PR DESCRIPTION
**Pull request by igeighty**
this fixes the monitor function for arma3 as @MPCP10 suggested

### CODE REVIEW

**Comment by UltimateByte** [comment]
So it's tested and working as you said ?

**Comment by igeighty** [comment]
Yes, I am using the default port value (2302) specified in line 35 of arma3server file (i still have the ports commented out in arma3-server.server.cfg) as these are not needed if you are specifying the port in the startup parameters.

the `./arma3server m` now queries 2303 correctly. as @MCPC10 says, it is the base port +1 that needed to be read. 

so working good now with the added lines. thank you.

**Comment by UltimateByte** [comment]
@dgibbs64 will review this and probably merge :)

**Comment by dgibbs64** [comment]
Good work 😁

**Comment by igeighty** [comment]
sorry i seem to have messed up the file edit that i uploaded..


i spelt the engine name incorrectly.. real virtuality i have double and triple checked it now, and will submit a new pull.

so sorry guys. i typed it manually and made the typo..

**Comment by JHulsmans** [comment]
Hey @igeighty happens to the best of us! Thanks for your contribution (again)

**Comment by igeighty** [comment]
no worries guys, first go at uploading and i bust it :)

**Pull request merged**
